### ISSUE TITLE
Different UI sets for users & developers

### ISSUE THREAD

**Issue by timdrysdale** [practable/relay#21]
## Feature request

Allow UI sets to be specified to suit different users (as opposed to current tight coupling of "one ui-set for all" at any given time for a given activity)

### Problem

When a course goes live, the users only want to be shown the "final" user interfaces, yet developers still need a way to access updated interfaces for testing.

### Proposal: 

We can consider aligning our UIsets globally with roles, or further split it up according to class /topic. We look at these options in what follows.

#### GLOBAL categories

Developers, course staff, course students typically need different UI sets:

a/ polished UI for course students
b/ a preview of upcoming changes for course staff
c/ debugger UIs to aid developers

We would specify access with scopes
```
ui
ui:final
ui:preview
ui:develop
```
Course staff and students would usually be given `ui:final`.
Prior to a course starting, course staff might get `ui:final,ui:preview` 
Developers get `ui`, i.e all subsidiary scopes including `ui:develop` are available to them by hierarchy

In the manifest, three UI sets can be specified. They should not contain overlapping entries.

##### Current manifest
```
  spinner-sim-95:
    description: spinner-sim-v1.0
    UISet: spinner-sim-v1.0
    exp: 	1654045200

<snip>

UISets:
  <snip>
  spinner-sim-v1.0:
  - spinner-sim-ui-1.0
```

##### Proposed new manifest 
For backwards compatibility, leave UISet key as it is 
Add new entry in activity description, which is plural UISets
Retain the flat list of UISets later in the manifest

```
  spinner-sim-95:
    description: spinner-sim-v1.0
    UISets:
      final: spinner-sim-v1.0-final
      preview: spinner-sim-v1.0-preview
      develop: generic-debug-ui
    exp: 	1654045200

UISets:
  <snip>
  spinner-sim-v1.0-final:
  - spinner-sim-ui-1.0
  spinner-sim-v1.0-preview:
  - spinner-sim-ui-1.1
  generic-debug-ui:
  - debug-ui-1.0
  - dev-debug-ui-1.0
```

#### CLASS categories
We can build on the previous specification by adding class scopes to the specification of each activity.

```
  spinner-sim-95:
    description: spinner-sim-v1.0
    UISets:
      final: 
        - scope: ugee0000
          UISet: spinner-sim-v1.0-velocity-final
        - scope: pgee1111
          UISet: spinner-sim-v1.0-position-final
      preview: 
        - scope: ugee0000
          UISet: spinner-sim-v1.0-velocity-final
        - scope: pgee1111
          UISet: spinner-sim-v1.0-position-final
      develop: generic-debug-ui
    exp: 	1654045200
```
Note that the choice to put final/preview/develop as first level of hierarchy and not class, creates quite long entries, however, it is sufficiently expressive and obvious. Overlap between UIs in the class scopes IS permitted.

Example: a student on a course would get a link with the scope 'ui:final:pgee1111,` which should not cause any issues if there is a second experiment on their course because that experiment will also be issuing the same scope.

###### Swapping scope hierarchy (spoiler: won't) 
The alternative of assigning user scopes to UIs directly is going to make it easier to make mistakes about who can see what, or to use the same ui in different ways (e.g. a ui might be the final ui for one class with one type of hardware, and only the development ui for new hardware for another class).

## Exhibits
It would be helpful for a QR code to be able to direct someone to a specific single instance of a UI for a given exhibit (coupled with a booking app operating in silent mode, which hides any other activities). This can most likely be accomplished by an appropriate URL parameter in the QR code, saying "exhibit mode", and supplying the pool name to book and ui name to use. This would work with either global or class scopes in place, because the pool name and the ui name would be (by convention) uniquely set in the description (although uniqueness is not enforced by the manifest in the description contents, it is in the keys - and this could be added as a sanity check if it is sufficiently globally applicable)
