### ISSUE TITLE
Change shell command to avoid conflict

### ISSUE THREAD

**Issue by timdrysdale** [practable/relay#5]
The shell command does not exist, but issuing `pkill shell` could have unintended consequences on some systems where this name is also used for the main shell - so this command needs to have a different name, probably shellrelay. This mainly affects your ansible host where running a bunch of shell clients it is tempting to issue 'pkill shell' to shut them down ...

**Comment by timdrysdale** [comment]
Same issue applies for `pkill session` and the possibility of hitting enter too soon when using a modified form of the name such as `session-relay`. So we want to get away from using names that can cause problems by simple mistakes. Perhaps a better approach would be to have a single command, 'practable' that takes care of _all_ of the necessary activities, similar to how `kubectl` and 'gcloud` contain many sublevels of commands. The `book`/`session`/`shell`executables are currently about 15-17MB each, although presumably they share common code so this figure will not rise too much upon combination.  [Kubectl v1.15 was 41M](https://github.com/kubernetes/minikube/issues/5013#issuecomment-533776469) for comparison. Adding additional commands for new features will be optional, in that there is nothing stopping a separately developed repo from playing with the ecosystem during development - and upon maturation, can be incorporated into the  `practable` command.

There is also the benefit of then only needing a single image to supply all of the necessary commands to set up a system, and if we produce the image with an [entrypoint](https://www.cloudbees.com/blog/understanding-dockers-cmd-and-entrypoint-instructions) of `practable`,  i.e. 
```
ENTRYPOINT ["practable"]
```
then we can set up the subcommand as required in the k8s deployments, pby specifying args](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/):
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: practable-demo
  labels:
    purpose: demo-entry-args
spec:
  containers:
  - name: practable-demo
    image: practable/practable-0.x.y
    args: ["book", "serve"]
    ports:
    -  containerPort: 4000
        name: book-api-port  
    envFrom:
      - configMapRef:
          name: book-cm
  restartPolicy: OnFailure
```

Some possible commands

`practable help`
`practable book [getstatus/reset/serve/setstatus/token/upload]`
`practable data [client/host/relay/token]`
`practable ssh [client/host/relay/token]`
 
This then leaves working out a suitable set of environment variables, avoiding unnecessary duplication.
